name: Deploy Medusa on AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1
        aws ecr get-login-password | docker login --username AWS --password-stdin <AWS_ECR_URL>

    - name: Build and push Docker image
      run: |
        docker build -t <ECR_REPO_URL>:latest .
        docker push <ECR_REPO_URL>:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster medusa-cluster --service medusa-service --force-new-deployment
